version: '3.7'
services:
  unifi:
    build: .
    user: 1000:1000
    volumes:
      - ./data:/usr/lib/unifi/data
    ports:
      - 6789:6789
      - 8080:8080
      - 8443:8443
      - 8880:8880
      - 8843:8843
      - 3478:3478/udp
  mongo:
    image: mongo:3.6
